### ISSUE TITLE
Fix GC with recombination rate = 0

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#851]
Gene conversion currently doesn't work with recombination rate at zero. Need to figure out the correct workaround for this.

**Comment by jeromekelleher** [comment]
This should be resolved now after #862; can you have a look please @fbaumdicker?

**Comment by fbaumdicker** [comment]
It is not resolved yet. If the recombination rate is zero the gene conversion within rate is also set to zero which should not be the case. One solution would be to create a uniform recombination map with recombination rate 1 and set a flag `recombination_is_nonzero` that remembers whether the actual recombination rate is zero.

When the current lambda in msp_run_coalescent for the recombination rate is calculated  we use
`recomb_mass * recombination_is_nonzero`

I can try to implement something like this?

**Comment by jeromekelleher** [comment]
I don't follow why the GC start position rate would follow the recombination rate everywhere except zero regions @fbaumdicker. Wouldn't it be simpler (and easier to explain) if we just let the GC start point track the recombination map for now? We'll probably want to do something more complicated later where the GC start position has its own variable rate map, and this could capture the functionality that you're thinking about here.

**Comment by jeromekelleher** [comment]
Ah yes, when recombination is zero **everywhere** we have a problem. Hmm, this is awkward.

**Comment by fbaumdicker** [comment]
Yes, I am not talking about an alternative GC start position map. I think this is currently not of interest. Instead, I want to be able to simulate e.g. the ms command
`ms 10 1 -t 1.0 -r 0 100 -c 2 5`
I think it should be okay to define a "fake" uniform recombination map in this scenario, as there is no recombination in the model anyway.

**Comment by jeromekelleher** [comment]
Thinking about this a bit more, I think the only clean way to do this is to have a separate Fenwick tree tracking the GC rates (we'll want a second also for perf). So, we can get GC start positions changing along the genome, and this is the right way to parameterise things for the low-level simulations. So, the first thing we want to do here is to make a IntervalMap which allows us to specify rates along the genome, #920.

**Comment by fbaumdicker** [comment]
Yes, that sounds like a good plan. And it would solve this issue without confusing tricks.

Two comments:

1. For performance, it might be worth including the (possibly common) case where the gene conversion rate is proportional to the recombination rate along the whole map. In this case, we can get all the necessary information for the internal gc events from the recombination_map and the corresponding Fenwick tree. So we could easily improve perf here.
2. If we want to include gc with variable rates we have to change the way gene conversions from the left are currently handled. Basically we will need another Fenwick tree tracking the rates at which gc events extend from the left side into the segments. For this, we will also have to compute the rate from the left for each position given the IntervalMap.

**Comment by jeromekelleher** [comment]
Sounds good, thanks @fbaumdicker. I'll work up the basic changes soon and ping you for input then.
